Repository ncsu-landscape-dynamics/popsborder, pull requests merged in 2022-03, with the labels that each got.

#153 Add unique contamination per consignment origin and commodity
  docs/contamination.md
  popsborder/consignments.py
  popsborder/contamination.py
  popsborder/inputs.py
  tests/test_contamination.py
  tests/test_inputs.py
Labels: enhancement

#168 correct git install to secure URL
  docs/conda_windows_install.md
Labels: documentation

#172 Create config files in notebook data dir
  examples/notebooks/basic_with_command_line.ipynb
  examples/notebooks/simple.yml
Labels: bug, enhancement

#173 Add main page for docs, fix link in readme
  README.md
  docs/README.md
Labels: documentation

#169 Convert to pandas from one result with all columns
  popsborder/outputs.py
  tests/test_summaries.py
Labels: enhancement

#174 Replace remaining shipment in doc, fix typos
  docs/use_cases.md
  popsborder/consignments.py
  popsborder/outputs.py
Labels: bug, documentation

#178 Add date property to Consignment
  popsborder/consignments.py
  tests/test_consignments.py
Labels: bug

#179 Fix attribute access to arbitrary consignmenty properties
  popsborder/consignments.py
  tests/test_consignments.py
Labels: bug

#182 Use case updates
  examples/Montgomery_2021/data/consignment_scenarios.csv
  examples/Montgomery_2021/data/contamination_rate_estimation.csv
  examples/Montgomery_2021/simulation_use_cases.ipynb
Labels: documentation
