Repository ncsu-landscape-dynamics/popsborder, pull requests merged in 2022-02, with the labels that each got.

#154 Use f-strings, fix pretty style error message
  popsborder/app.py
  popsborder/inputs.py
  popsborder/outputs.py
  popsborder/simulation.py
Labels: refactoring

#155 Fix typos in the doc
  docs/inspections.md
  popsborder/outputs.py
Labels: bug, documentation

#156 Fix re-raising exceptions, simplify min, max, super
  popsborder/app.py
  popsborder/consignments.py
  popsborder/inspections.py
Labels: refactoring

#150 popsborder install instructions for conda on Windows
  docs/conda_windows_install.md
Labels: documentation

#157 Fix typos in the documentation
  docs/run.md
  docs/use_cases.md
  popsborder/contamination.py
Labels: bug, documentation

#158 Use isort to isort import, add config file
  examples/python/scenarios.py
  popsborder/app.py
  popsborder/inspections.py
  popsborder/outputs.py
  popsborder/scenarios.py
  pyproject.toml
  tests/test_cli.py
  tests/test_contaminant_clusters_basic_distributions.py
  tests/test_inspections.py
  tests/test_run_simulation.py
  tests/test_scenarios.py
  tests/test_summaries.py
Labels: enhancement, refactoring

#159 Fix example Bash scripts
  .editorconfig
  examples/bash/bash_examples.sh
  examples/bash/generate_synthetic_F280_dataset.sh
Labels: bug

#151 Add Cut Flower Release Program
  docs/cfrp.md
  docs/inspections.md
  popsborder/inputs.py
  popsborder/inspections.py
  popsborder/simulation.py
  popsborder/skipping.py
  tests/test_cfrp.py
  tests/test_skipping.py
Labels: enhancement
